- createlinks
- nethserver-sssd.spec
- root/etc/e-smith/templates/etc/samba/smb.conf/10base
Realm and keytab configuration for samba client tools
See NethServer/nethserver-samba#8
> Basic smb.conf

- root/usr/share/nethesis/NethServer/Module/Account/AuthProvider/Authenticate.php
- root/usr/share/nethesis/NethServer/Module/Account/AuthProvider/Index.php
Show Users & Groups view after successful domain join operation.
NethServer/dev#5097
> Reload Account module after join NethServer/dev#5097

- root/etc/e-smith/templates/etc/samba/smb.conf/10base
- root/etc/sudoers.d/20_nethserver_sssd
- root/usr/libexec/nethserver/smbads
- root/usr/share/nethesis/NethServer/Module/Sssd/Index.php
> Truncate NetBIOS names to 15 chars NethServer/dev#5110

- root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Account.php
- root/usr/share/nethesis/NethServer/Module/Account/AuthProvider/Index.php
- root/usr/share/nethesis/NethServer/Template/Account/AuthProvider/Index.php
> Web UI: display NetBIOS domain in join page

- root/usr/share/nethesis/NethServer/Help/en/NethServer_Module_Account.rst
- root/usr/share/nethesis/NethServer/Module/Account/AuthProvider/Index.php
- Pick the "leftmost label in the DNS domain name"
- Truncate to 15 chars
- Show it uppercase
NethServer/dev#5124
> Fix the NetBIOS domain calculation NethServer/dev#5124

- root/usr/share/nethesis/NethServer/Module/Account/Type/User/Modify.php
> Hide clear-text passwords in /var/log/secure

- root/usr/share/nethesis/NethServer/Help/en/NethServer_Module_Password.rst
https://github.com/NethServer/dev/issues/5135
> Inline help for Password Policies - Issue #5135

- root/usr/share/nethesis/NethServer/Module/Password.php
> Web UI: hide "Password policies" page if no provider is installed

- root/etc/e-smith/templates/etc/sssd/sssd.conf/20domain
> sssd.conf: override homedir when joining AD

- README.rst
- lib/perl/NethServer/SSSD.pm
> NethServer::SSSD return ldapservice credentials NethServer/dev#5145

- root/etc/e-smith/templates/etc/sssd/sssd.conf/01provider_config_remoteldap
> Remote LDAP account provider support NethServer/dev#5158

- root/etc/nethserver/system-groups
filter out nfsnobody group introduced by @nethserver-backup dependencies
> filter out nfsnobody group

- root/etc/nethserver/system-users
filter out nfsnobody user introduced with @nethserver-backup dependencies
> filter out nfsnobody user

- root/etc/e-smith/db/configuration/defaults/admins/group
- root/etc/e-smith/db/configuration/defaults/admins/type
- root/etc/e-smith/db/configuration/defaults/admins/user
> Create default "admins" record NethServer/dev#5157

- README.rst
- createlinks
- lib/perl/NethServer/SSSD.pm
- root/etc/e-smith/templates/etc/openldap/ldap.conf/10default
- root/etc/e-smith/templates/etc/openldap/ldap.conf/20tls
- root/etc/e-smith/templates/etc/sssd/sssd.conf/00template_vars
- root/etc/e-smith/templates/etc/sssd/sssd.conf/01provider_config
- root/etc/e-smith/templates/etc/sssd/sssd.conf/01provider_config_remoteldap
- root/usr/libexec/nethserver/pam-authenticate
NethServer/dev#5158
NethServer/dev#5161
> Read sssd.conf defaults from NethServer::SSSD

- lib/perl/NethServer/SSSD.pm
- root/usr/libexec/nethserver/pam-authenticate
> Use ldaps:// to bind AD NethServer/dev#5161

- createlinks
- root/etc/e-smith/events/actions/nethserver-sssd-notifyclients
The new nethserver-sssd-notifyclients searches which RPM uses
NethServer::SSSD and invokes its *-update event.
NethServer/dev#5164
> Replace system-adjust action NethServer/dev#5164

- README.rst
- lib/perl/NethServer/AccountsList.pm
- root/etc/e-smith/events/actions/nethserver-sssd-clear-cache
- root/etc/e-smith/templates/etc/sssd/sssd.conf/01provider_config
- root/etc/nethserver/system-groups
- root/etc/nethserver/system-users
- root/etc/sudoers.d/20_nethserver_sssd
- root/usr/libexec/nethserver/count-accounts
- root/usr/libexec/nethserver/list-group-members
- root/usr/libexec/nethserver/list-groups
- root/usr/libexec/nethserver/list-user-membership
- root/usr/libexec/nethserver/list-users
- root/usr/share/nethesis/NethServer/Module/Account/Type/Group/Modify.php
- root/usr/share/nethesis/NethServer/Module/Account/Type/User/Modify.php
- root/usr/share/nethesis/NethServer/Module/Dashboard/SystemStatus/Accounts.php
- root/usr/share/nethesis/NethServer/Tool/GroupProvider.php
- root/usr/share/nethesis/NethServer/Tool/UserProvider.php
> Universal LDAP browse scripts NethServer/dev#5168

- lib/perl/NethServer/SSSD.pm
- root/usr/libexec/nethserver/count-accounts
- root/usr/libexec/nethserver/list-group-members
- root/usr/libexec/nethserver/list-groups
- root/usr/libexec/nethserver/list-user-membership
- root/usr/libexec/nethserver/list-users
- root/usr/libexec/nethserver/sssd-defaults
- root/usr/share/nethesis/NethServer/Help/en/NethServer_Module_SssdConfig.rst
- root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Account.php
- root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_SssdConfig.php
- root/usr/share/nethesis/NethServer/Module/Dashboard/SystemStatus/Accounts.php
- root/usr/share/nethesis/NethServer/Module/SssdConfig/AuthProvider/Authenticate.php
- root/usr/share/nethesis/NethServer/Module/SssdConfig/AuthProvider/Index.php
- root/usr/share/nethesis/NethServer/Tool/BaseProvider.php
> SssdConfig page QA tweaks

- lib/perl/NethServer/SSSD.pm
- root/etc/e-smith/templates/etc/sssd/sssd.conf/20domain_primary
- root/etc/e-smith/templates/etc/sssd/sssd.conf/21domain_legacy
- root/usr/libexec/nethserver/count-accounts
- root/usr/libexec/nethserver/list-group-members
- root/usr/libexec/nethserver/list-groups
- root/usr/libexec/nethserver/list-user-membership
- root/usr/libexec/nethserver/list-users
- root/usr/libexec/nethserver/sssd-defaults
- root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Account.php
- root/usr/share/nethesis/NethServer/Module/SssdConfig.php
- root/usr/share/nethesis/NethServer/Template/SssdConfig/AuthProvider/Index.php
- root/usr/share/nethesis/NethServer/Tool/BaseProvider.php
> SssdConfig page QA tweaks 2

- root/usr/share/nethesis/NethServer/Tool/GroupProvider.php
- root/usr/share/nethesis/NethServer/Tool/UserProvider.php
> Sort UI helper lists

- README.rst
> Revert Account Import scripts section

- root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Account.php
> Web interface: add missing account provider errors.

- root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Account.php
- root/usr/share/nethesis/NethServer/Module/Sssd.php
- root/usr/share/nethesis/NethServer/Module/Sssd/Index.php
- root/usr/share/nethesis/NethServer/Template/Account/NoConfig.php
- root/usr/share/nethesis/NethServer/Template/Sssd/Index.php
If an accounts provider is not yet configured, print some background
information about accounts providers to help the sysadmin on deciding.
NethServer/dev#5215
> Additional information about accounts providers

- nethserver-sssd.spec
- root/etc/backup-config.d/nethserver-sssd.include
- root/etc/e-smith/events/actions/nethserver-sssd-backup-tdb
> Fix backup of Samba secrets.tdb

- createlinks
- nethserver-sssd.spec
- root/etc/e-smith/events/actions/nethserver-sssd-conf
- root/etc/e-smith/events/actions/nethserver-sssd-restore-ns6ads
- root/etc/e-smith/events/actions/nethserver-sssd-restore-ns6hostname
If the backup has smb/ServerRole=ADS, configure a remote AD accounts
provider.
NethServer/dev#5234
> Upgrade ns6 ADS ServerRole

- README.rst
- createlinks
- root/etc/e-smith/events/actions/nethserver-sssd-export-accounts
- root/etc/e-smith/events/actions/nethserver-sssd-remove-provider
- scripts/import_groups
- Add new account-provider-remove event
- Add script for bulk groups import
NethServer/dev#5252
> Reset account provider

- lib/perl/NethServer/LdapCli.pm
- lib/perl/NethServer/LdapClient.pm
- root/etc/e-smith/events/actions/nethserver-sssd-cleanup
- root/usr/libexec/nethserver/count-accounts
- root/usr/libexec/nethserver/list-group-members
- root/usr/libexec/nethserver/list-groups
- root/usr/libexec/nethserver/list-user-membership
- root/usr/libexec/nethserver/list-users
* GSSAPI auth
* LDAP paged search
> LDAP client improvements

- root/etc/e-smith/db/configuration/migrate/issue5253.ns7
Avoid dnsmasq wrong configuration if Realm property is not set.
Replaces #58 
> db migration: calculate Realm prop

- root/etc/e-smith/templates/etc/dnsmasq.conf/50sssd
It occurs during restore-config.
NethServer/dev#5234
> Fix template expansion warning

- createlinks
- root/etc/e-smith/events/actions/nethserver-sssd-migrate
Fixes a regression due to the new Workgroup prop under sssd key
> Migrate Workgroup prop

- root/etc/e-smith/validators/actions/ipgreenandbridged
Thanks @filippocarletti for the ``arping`` command.
Closes #64
> Check IP is free with arping

- root/etc/e-smith/db/configuration/migrate/issue5253.ns7
- root/etc/e-smith/templates/etc/samba/smb.conf/10base
- root/usr/share/nethesis/NethServer/Module/SssdConfig/LocalAdProvider.php
- root/usr/share/nethesis/NethServer/Module/SssdConfig/LocalLdapUpgrade.php
- root/usr/share/nethesis/NethServer/Module/SssdConfig/Wizard/AdNewDomain.php
- root/usr/share/nethesis/NethServer/Template/SssdConfig/LocalLdapUpgrade.php
- root/usr/share/nethesis/NethServer/Template/SssdConfig/Wizard/AdNewDomain.php
- initialize, migrate, upgrade Realm and Workgroup props correctly
- fix case when DNS domain name and NetBIOS domain name are shown
- ask for DNS domain name and IP to upgrade LDAP/ns6 to AD
NethServer/dev#5234
> NS6 upgrade form

- createlinks
- root/etc/e-smith/events/actions/nethserver-sssd-set-workgroup
> post-restore-config: set workgroup for NS 6 upgrade

- root/etc/e-smith/events/actions/nethserver-sssd-migrate
> Retain original Workgroup in WS migration

- root/etc/e-smith/events/actions/nethserver-sssd-restore-ns6hostname
- root/usr/share/nethesis/NethServer/Module/SssdConfig/LocalLdapProvider.php
> ns6 upgrade: always restore FQDN

- lib/perl/NethServer/AccountsList.pm
- lib/perl/NethServer/LdapClient.pm
- root/etc/e-smith/events/actions/nethserver-sssd-notifyclients
> Fix Perl modules

- lib/perl/NethServer/LdapClient.pm
> LdapClient: add bind for ldapi://

- root/usr/libexec/nethserver/list-users
> list-users: return 'yes' and 'no' for AD password expiration

- README.rst
- root/usr/share/nethesis/NethServer/Module/Password.php
- root/usr/share/nethesis/NethServer/Template/Password.php
The notification messages are not implemented on ns7.
NethServer/dev#5318
> Remove Password warning slider

- root/usr/share/nethesis/NethServer/Module/SssdConfig/RemoteAdProvider.php
Mimic behavior from RemoteLdapProvider class:
apply changes to all applications which use
NethServer:SSSD library.
NethServer/dev#5377
> UI: execute nethserver-sssd-save on AD options change

- .travis.yml
- root/usr/share/nethesis/NethServer/Template/User/Modify.php
relative to https://github.com/NethServer/dev/issues/5391
> remove the shell disabled state for AD

- root/usr/share/nethesis/NethServer/Module/SssdConfig/Wizard/AdJoinMember.php
> Forced to leave before join

- root/usr/share/nethesis/NethServer/Module/SssdConfig/RemoteLdapProvider.php
> Fix StartTls argument for ldap-credentials validator

- .travis.yml
This is the new environment variable that obsoletes UPLOAD_DEST
> Use ENDPOINTS_PACK variable

- lib/perl/NethServer/LdapClient.pm
Fixes long timeouts if DNS is not available (hotsync-promote,
restore-config), that cause the Dashboard and other UI pages to hang.
NethServer/dev#5434
---
See also
http://search.cpan.org/~nlnetlabs/Net-DNS-1.15/lib/Net/DNS/Resolver.pm#tcp_timeout
> LdapClient: apply "timeout" option to DNS resolver

- createlinks
- root/etc/e-smith/events/actions/nethserver-sssd-ns6homes
This happens in post-restore-data event
NethServer/dev#5432
> Reset home dir permissions during ns6 upgrade

- root/etc/sudoers.d/20_nethserver_sssd
- root/usr/libexec/nethserver/net-ads-info
- root/usr/share/nethesis/NethServer/Module/Sssd/Index.php
- root/usr/share/nethesis/NethServer/Tool/GroupProvider.php
- root/usr/share/nethesis/NethServer/Tool/UserProvider.php
> Prevent net ads blocking if AD is unreachable

- createlinks
- root/etc/e-smith/templates/etc/krb5.conf/10base
This is the RHEL recommended setting:
https://access.redhat.com/articles/3023951
NethServer/dev#5535
> Template of krb5.conf

- root/usr/share/nethesis/NethServer/Template/SssdConfig/RemoteAdProvider.php
https://github.com/NethServer/dev/issues/5554
> mask password field

- root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Dashboard_SystemStatus_Accounts.php
NethServer/dev#5596
Edit the pseudonym label in Dashboard.
> Edit pseudonym label

- scripts/delete_users
https://github.com/NethServer/dev/issues/5657
> Admin script to delete users

- root/usr/libexec/nethserver/list-users
> Display expired AD accounts as pwd-expired

- root/etc/e-smith/templates/etc/krb5.conf/00template_vars
- root/etc/e-smith/templates/etc/krb5.conf/10base
- root/etc/e-smith/templates/etc/krb5.conf/20realms
> Honor sssd/DiscoverDcType prop

- nethserver-sssd.spec
- root/usr/libexec/nethserver/smbads
https://github.com/NethServer/dev/issues/5840
> Fix net ads invocation for Samba release 4.9

- README.rst
- root/etc/e-smith/db/configuration/defaults/sssd/ShellOverrideStatus
- root/etc/e-smith/templates/etc/sssd/sssd.conf/01provider_force_shell
https://github.com/NethServer/dev/issues/6029
> Prop to force the bash shell (disabled by default)
